name: snowpark_060
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.8
  - pip
  - pip:
    - './include/snowflake_snowpark_python-0.6.0-py3-none-any.whl[pandas]'
    - pytorch-tabnet==3.1.1
    - matplotlib==3.5.2
    - statsmodels==0.13.2
    - seaborn==0.11.2
    - rexmex==0.1.0
    - ipykernel==6.13.0
    - streamlit==1.8.1
